apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: posts
  template:
    metadata:
      labels:
        pod: posts
    spec:
      containers:
        - name: posts
          image: neeejm/posts:0.0.1