name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - main

jobs:
  CI:
    name: Running CI to build / push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push posts
        uses: docker/build-push-action@v2
        with:
          context: ./posts
          file: ./posts/Dockerfile
          push: true
          tags: neeejm/blog-posts:latest

      - name: Build and push event bus
        uses: docker/build-push-action@v2
        with:
          context: ./event-bus
          file: ./event-bus/Dockerfile
          push: true
          tags: neeejm/blog-event-bus:latest

      - name: Build and push comments
        uses: docker/build-push-action@v2
        with:
          context: ./comments
          file: ./comments/Dockerfile
          push: true
          tags: neeejm/blog-comments-bus:latest

      - name: Build and push query
        uses: docker/build-push-action@v2
        with:
          context: ./query
          file: ./query/Dockerfile
          push: true
          tags: neeejm/blog-query:latest

      - name: Build and push moderation
        uses: docker/build-push-action@v2
        with:
          context: ./moderation
          file: ./moderation/Dockerfile
          push: true
          tags: neeejm/moderation:latest
